# Generated by Django 3.0.5 on 2020-05-20 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0002_auto_20200519_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='profileImg',
            field=models.ImageField(default='Fpics/userpic.gif', upload_to='Fpics'),
        ),
    ]
